version: '2.4'

services:
  codeserver:
    container_name: codeserver
    build:
      context: dockerfile
      args:
        UID: ${UID}
        GID: ${GID}
        GIT_NAME: ${GIT_NAME}
        GIT_EMAIL: ${GIT_EMAIL}
    restart: unless-stopped
    user: ${UID}:${GID}
    volumes:
      - "./app_data:/user_home/.local:rw"
      - "./config:/user_home/.config:rw"
      - "./data:/user_home/data:rw"
      - "./ssh:/user_home/.ssh:rw"
    environment:
      EXTENSIONS_GALLERY: '{"serviceUrl": "https://marketplace.visualstudio.com/_apis/public/gallery","cacheUrl":"https://vscode.blob.core.windows.net/gallery/index","itemUrl":"https://marketplace.visualstudio.com/items"}'
    networks:
      - proxy
    # security_opt:
    #   - apparmor:unconfined
    # cap_add:
    #   - SYS_ADMIN
    mem_limit: 8G

networks:
  proxy:
    external:
      name: proxy
